### PR TITLE
Shall we call this "taking the trash out" ?

### PR DESCRIPTION
**Pull request by Antes**
This is not really a finished PR, but for starting it takes out the trash which is removed with SMF2.1. Some places are broken, some are lacking styling but as i said its enough for starting.

### CODE REVIEW

**Comment by Antes** [comment]
I'm not sure what is causing this "conflict" but It would be nice to know :P.

**Comment by jdarwood007** [comment]
This broke a few things, but it is going to be easier to fix them now that this has been merged in.

**Comment by Antes** [comment]
Yea, I'm aware of those broken things but due to my personal schedule I can start working on both SD/SMF after 8 of Jan :(

FYI: This work is not complete there are lots of things needs to be changed, especially icons used here mostly inside SMF2.1's default image sprite.

**Comment by jdarwood007** [comment]
No problem, just pushed up a fix that does some patching to the things I can notice right away.  Most of it is due to the ids being removed which are needed by the javascript to do fancy stuff.

**Pull request merged**
